enablePrePostScripts: true
minimumReleaseAge: 0
nodeLinker: hoisted
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 day

allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
